### ISSUE TITLE
Request/Handlers bottle neck + DDOS preventation

### ISSUE THREAD

**Issue by Amadeus899** [rarimo/passport-identity-provider#4]
Заметил что этот хендлер очень нагружен (как возможно и другие публичные ручки) и может оказаться "узким горлышком" в процессе предстоящих DDOS атак. 
https://github.com/rarimo/passport-identity-provider/blob/57fedf023e19b7af11a59c272b2f89e2bcaf61e1/internal/service/api/handlers/create_identity.go#L56

Так же не смог найти в коде каких-либо использований throttle и/или rate limiters. Их точно стоит внедрить либо в коде, либо уже на инфраструктурном уровне nginx. Так как вряд ли предполагается что один пользователь будет отсылать много запросов, то можно ограничиться в 3-5 RPM для одного IP адреса.

**Comment by freigeistig** [comment]
Yes, we are aware of this. Thank you for your advice.
