### ISSUE TITLE
SHA1 Issue

### ISSUE THREAD

**Issue by Amadeus899** [rarimo/passport-identity-provider#5]
В принципе уже подмечал в клиентских репозиториях, однако здесь тоже продублирую. Возможно стоит убрать SHA1 алгоритм и заменить его на SHA2(56)? Ибо первая версия уже не рекомендована к использованию.

https://github.com/rarimo/passport-identity-provider/blob/57fedf023e19b7af11a59c272b2f89e2bcaf61e1/internal/service/api/handlers/create_identity.go#L48

**Comment by freigeistig** [comment]
SHA1 is used in some passport digital signature algorithms, so it is impossible to get rid of it if we want to support them. You can check `verifySignature` function in the `/internal/service/api/handlers/create_identity.go` file to see the process of passport signature verification and SHA1 role in it.
